package gregtechmod.loaders.preload;

import gregtechmod.api.util.GT_Log;
import gregtechmod.loaders.oreprocessing.ProcessingBattery;
import gregtechmod.loaders.oreprocessing.ProcessingBlock;
import gregtechmod.loaders.oreprocessing.ProcessingBolt;
import gregtechmod.loaders.oreprocessing.ProcessingCell;
import gregtechmod.loaders.oreprocessing.ProcessingCellPlasma;
import gregtechmod.loaders.oreprocessing.ProcessingCircuit;
import gregtechmod.loaders.oreprocessing.ProcessingCrafting;
import gregtechmod.loaders.oreprocessing.ProcessingCrushed;
import gregtechmod.loaders.oreprocessing.ProcessingCrushedCentrifuged;
import gregtechmod.loaders.oreprocessing.ProcessingCrushedPurified;
import gregtechmod.loaders.oreprocessing.ProcessingDust;
import gregtechmod.loaders.oreprocessing.ProcessingDustImpure;
import gregtechmod.loaders.oreprocessing.ProcessingDustSmall;
import gregtechmod.loaders.oreprocessing.ProcessingDustTiny;
import gregtechmod.loaders.oreprocessing.ProcessingDye;
import gregtechmod.loaders.oreprocessing.ProcessingGear;
import gregtechmod.loaders.oreprocessing.ProcessingGem;
import gregtechmod.loaders.oreprocessing.ProcessingIngot1;
import gregtechmod.loaders.oreprocessing.ProcessingIngot2;
import gregtechmod.loaders.oreprocessing.ProcessingIngot3;
import gregtechmod.loaders.oreprocessing.ProcessingIngot4;
import gregtechmod.loaders.oreprocessing.ProcessingIngot5;
import gregtechmod.loaders.oreprocessing.ProcessingIngotHot;
import gregtechmod.loaders.oreprocessing.ProcessingItem;
import gregtechmod.loaders.oreprocessing.ProcessingLeaves;
import gregtechmod.loaders.oreprocessing.ProcessingLog;
import gregtechmod.loaders.oreprocessing.ProcessingNugget;
import gregtechmod.loaders.oreprocessing.ProcessingOre;
import gregtechmod.loaders.oreprocessing.ProcessingOreSmelting;
import gregtechmod.loaders.oreprocessing.ProcessingPlank;
import gregtechmod.loaders.oreprocessing.ProcessingPlate1;
import gregtechmod.loaders.oreprocessing.ProcessingPlate2;
import gregtechmod.loaders.oreprocessing.ProcessingPlate3;
import gregtechmod.loaders.oreprocessing.ProcessingPlate4;
import gregtechmod.loaders.oreprocessing.ProcessingPlate5;
import gregtechmod.loaders.oreprocessing.ProcessingPlate9;
import gregtechmod.loaders.oreprocessing.ProcessingPlateAlloy;
import gregtechmod.loaders.oreprocessing.ProcessingRecycling;
import gregtechmod.loaders.oreprocessing.ProcessingRing;
import gregtechmod.loaders.oreprocessing.ProcessingSand;
import gregtechmod.loaders.oreprocessing.ProcessingSaplings;
import gregtechmod.loaders.oreprocessing.ProcessingShaping;
import gregtechmod.loaders.oreprocessing.ProcessingSlab;
import gregtechmod.loaders.oreprocessing.ProcessingStick;
import gregtechmod.loaders.oreprocessing.ProcessingStone;
import gregtechmod.loaders.oreprocessing.ProcessingStoneCobble;
import gregtechmod.loaders.oreprocessing.ProcessingStoneVarious;
import gregtechmod.loaders.oreprocessing.ProcessingToolHeadAxe;
import gregtechmod.loaders.oreprocessing.ProcessingToolHeadFile;
import gregtechmod.loaders.oreprocessing.ProcessingToolHeadHammer;
import gregtechmod.loaders.oreprocessing.ProcessingToolHeadHoe;
import gregtechmod.loaders.oreprocessing.ProcessingToolHeadPickaxe;
import gregtechmod.loaders.oreprocessing.ProcessingToolHeadSaw;
import gregtechmod.loaders.oreprocessing.ProcessingToolHeadShovel;
import gregtechmod.loaders.oreprocessing.ProcessingToolHeadSword;
import gregtechmod.loaders.oreprocessing.ProcessingWax;

public class GT_OreProcessingLoader implements Runnable {

   public void run() {
      GT_Log.log.info("GT_Mod: Register Ore processing.");
      new ProcessingBattery();
      new ProcessingBlock();
      new ProcessingBolt();
      new ProcessingCell();
      new ProcessingCellPlasma();
      new ProcessingCircuit();
      new ProcessingCrafting();
      new ProcessingCrushed();
      new ProcessingCrushedPurified();
      new ProcessingCrushedCentrifuged();
      new ProcessingDust();
      new ProcessingDustImpure();
      new ProcessingDustSmall();
      new ProcessingDustTiny();
      new ProcessingDye();
      new ProcessingShaping();
      new ProcessingGem();
      new ProcessingGear();
      new ProcessingIngot1();
      new ProcessingIngot2();
      new ProcessingIngot3();
      new ProcessingIngot4();
      new ProcessingIngot5();
      new ProcessingIngotHot();
      new ProcessingItem();
      new ProcessingLeaves();
      new ProcessingLog();
      new ProcessingNugget();
      new ProcessingOre();
      new ProcessingOreSmelting();
      new ProcessingPlank();
//      new ProcessingPlate1();
//      new ProcessingPlate2();
//      new ProcessingPlate3();
//      new ProcessingPlate4();
//      new ProcessingPlate5();
//      new ProcessingPlate9();
      new ProcessingPlateAlloy();
      new ProcessingRecycling();
      new ProcessingRing();
      new ProcessingSand();
      new ProcessingSaplings();
      new ProcessingSlab();
      new ProcessingStick();
      new ProcessingStone();
      new ProcessingStoneCobble();
      new ProcessingStoneVarious();
      new ProcessingToolHeadAxe();
      new ProcessingToolHeadFile();
      new ProcessingToolHeadHammer();
      new ProcessingToolHeadHoe();
      new ProcessingToolHeadPickaxe();
      new ProcessingToolHeadSaw();
      new ProcessingToolHeadShovel();
      new ProcessingToolHeadSword();
      new ProcessingWax();
   }
}
