package gregtechmod.api.enums;

public enum GT_ConfigCategories {
	news,
	mortar,
	general,
	smelting,
	squeezer,
	machineconfig,
	liquidtransposer,
	liquidtransposerfilling,
	liquidtransposeremptying,
	extractor,
	sawmill,
	uumrecipe,
	compression,
	massfabamplifier,
	inductionsmelter,
	rcblastfurnace,
	maceration,
	boilerfuels,
	scrapboxdrops,
	harderrecipes,
	gregtechrecipes,
	disabledrecipes,
	blastfurnacerequirements, 
	recipereplacements,
	hammerplating,
	hammerdoubleingot,
	hammercrushing,
	storageblockcrafting,
	storageblockdecrafting,
	specialunificationtargets;
}